-- ── 1. Widen the type constraint on booking_profit_events ────────────────────
-- Add 'recognition' to allow the payment-triggered commission recognition event.
alter table booking_profit_events
  drop constraint if exists booking_profit_events_type_check;

alter table booking_profit_events
  add constraint booking_profit_events_type_check
    check (type in ('original', 'amendment', 'recognition'));

-- ── 2. Add commissionable flag ────────────────────────────────────────────────
-- default false — every existing row is non-commissionable until backfilled below.
alter table booking_profit_events
  add column if not exists commissionable boolean not null default false;

-- ── 3. Backfill existing rows ─────────────────────────────────────────────────
-- Events on bookings that already have balance_cleared_at set are commissionable.
-- Applies only to 'original' and 'amendment' — no 'recognition' rows exist yet.
update booking_profit_events bpe
set    commissionable = true
from   bookings b
where  bpe.booking_id = b.id
  and  b.balance_cleared_at is not null
  and  bpe.type in ('original', 'amendment');

-- ── 4. commission_cycles ──────────────────────────────────────────────────────
-- Period registry for future report locking. Building the report is a separate task.
create table if not exists commission_cycles (
  id         bigint generated by default as identity primary key,
  period     text        not null unique,          -- 'YYYY-MM'
  status     text        not null default 'open'
               check (status in ('open', 'locked')),
  locked_at  timestamptz,
  locked_by  integer references staff_users(id),
  created_at timestamptz not null default now()
);
