create table if not exists booking_commissions (
  id bigint generated by default as identity primary key,
  booking_id bigint not null references bookings(id) on delete cascade,
  staff_id integer not null references staff_users(id),
  share_percent numeric(5,2) not null,
  is_primary boolean not null default false,
  created_at timestamptz not null default now(),
  constraint booking_commissions_share_percent_check check (share_percent > 0 and share_percent <= 100)
);

create unique index if not exists booking_commissions_booking_staff_uidx
  on booking_commissions (booking_id, staff_id);

create unique index if not exists booking_commissions_primary_uidx
  on booking_commissions (booking_id)
  where is_primary = true;

create or replace function enforce_booking_commission_total()
returns trigger
language plpgsql
as $$
declare
  target_booking_id bigint;
  total numeric(7,2);
begin
  target_booking_id := coalesce(new.booking_id, old.booking_id);

  select coalesce(sum(share_percent), 0)
  into total
  from booking_commissions
  where booking_id = target_booking_id;

  if total <> 100 then
    raise exception 'Booking % commission shares must total 100, got %', target_booking_id, total;
  end if;

  return null;
end;
$$;

drop trigger if exists trg_enforce_booking_commission_total on booking_commissions;

create constraint trigger trg_enforce_booking_commission_total
after insert or update or delete on booking_commissions
deferrable initially deferred
for each row execute function enforce_booking_commission_total();

create table if not exists booking_profit_events (
  id bigint generated by default as identity primary key,
  booking_id bigint not null references bookings(id) on delete cascade,
  type text not null check (type in ('original', 'amendment')),
  profit_delta numeric(12,2) not null,
  created_at timestamptz not null default now()
);

insert into booking_commissions (booking_id, staff_id, share_percent, is_primary)
select b.id, b.staff_id, 100.00, true
from bookings b
where b.staff_id is not null
  and not exists (
    select 1
    from booking_commissions bc
    where bc.booking_id = b.id
  );

insert into booking_profit_events (booking_id, type, profit_delta)
select b.id, 'original', b.final_profit
from bookings b
where coalesce(b.final_profit, 0) <> 0
  and not exists (
    select 1
    from booking_profit_events bpe
    where bpe.booking_id = b.id
  );;
