create table if not exists booking_profit_allocations (
  id              bigint generated by default as identity primary key,
  profit_event_id bigint not null references booking_profit_events(id) on delete cascade,
  staff_id        integer not null references staff_users(id),
  share_percent   numeric(5,2) not null,
  profit_share    numeric(12,2) not null,
  created_at      timestamptz not null default now()
);

create index if not exists booking_profit_allocations_event_idx
  on booking_profit_allocations (profit_event_id);

create index if not exists booking_profit_allocations_staff_idx
  on booking_profit_allocations (staff_id);

insert into booking_profit_allocations (profit_event_id, staff_id, share_percent, profit_share)
select
  bpe.id,
  bc.staff_id,
  bc.share_percent,
  round(bpe.profit_delta * bc.share_percent / 100, 2)
from booking_profit_events bpe
join booking_commissions bc on bc.booking_id = bpe.booking_id
where not exists (
  select 1
  from booking_profit_allocations bpa
  where bpa.profit_event_id = bpe.id
);;
