
-- commission_payroll_sheets
-- One row per staff member per recognition period.
-- Created when a manager issues a payroll sheet; staff can review/dispute.
create table if not exists commission_payroll_sheets (
  id               bigint generated by default as identity primary key,
  period           text        not null
                     check (period ~ '^\d{4}-\d{2}$'),   -- recognition month
  staff_id         integer     not null references staff_users(id),
  payable_month    text        not null
                     check (payable_month ~ '^\d{4}-\d{2}$'), -- period + 1 month
  issued_at        timestamptz,                            -- null = draft only
  issued_by        integer     references staff_users(id),
  total_commission numeric(12,2) not null default 0,
  manual_bonus     numeric(12,2) not null default 0,
  total_payable    numeric(12,2) not null default 0,       -- commission + bonus, snapshotted
  status           text        not null default 'draft'
                     check (status in ('draft','issued','reviewed','disputed','confirmed')),
  reviewed_at      timestamptz,
  reviewed_by      integer     references staff_users(id),
  dispute_notes    text,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  unique (period, staff_id)
);

-- keep updated_at current
create or replace function set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_payroll_sheets_updated_at on commission_payroll_sheets;
create trigger trg_payroll_sheets_updated_at
  before update on commission_payroll_sheets
  for each row execute function set_updated_at();
;
