-- CLIENTS
create table clients (
    id bigint generated by default as identity primary key,
    first_name text,
    last_name text,
    email text,
    phone text,
    created_at timestamp default now()
);
-- DEALS (MAIN SALES PIPELINE)
create table deals (
    id bigint generated by default as identity primary key,
    client_id bigint references clients(id),
    title text,
    stage text default 'NEW_LEAD',
    deal_value numeric,
    departure_date date,
    source text,
    created_at timestamp default now()
);
-- ACTIVITIES (CALL / EMAIL / WHATSAPP)
create table activities (
    id bigint generated by default as identity primary key,
    deal_id bigint references deals(id),
    activity_type text,
    notes text,
    created_at timestamp default now()
);
-- QUOTES
create table quotes (
    id bigint generated by default as identity primary key,
    deal_id bigint references deals(id),
    hotel text,
    board_basis text,
    price numeric,
    version integer default 1,
    created_at timestamp default now()
);
-- BOOKINGS (CONFIRMED DEALS)
create table bookings (
    id bigint generated by default as identity primary key,
    deal_id bigint references deals(id),
    booking_reference text,
    deposit_received boolean default false,
    balance_due_date date,
    created_at timestamp default now()
);
-- BOOKING TASKS (OPERATIONS CHECKLIST)
create table booking_tasks (
    id bigint generated by default as identity primary key,
    booking_id bigint references bookings(id),
    task_name text,
    completed boolean default false,
    created_at timestamp default now()
);
