CREATE TABLE IF NOT EXISTS staff_users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  role text DEFAULT 'sales',
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT now()
);
