create table if not exists hotel_contracts (
  id integer generated by default as identity primary key,
  hotel_id integer not null references hotel_list(id) on delete cascade,
  name text not null,
  currency text not null default 'GBP',
  market text,
  supplier_reference text,
  default_board_basis text,
  status text not null default 'draft' check (status in ('draft', 'active', 'archived')),
  notes text,
  created_at timestamptz not null default now()
);

create unique index if not exists hotel_contracts_hotel_name_uq
  on hotel_contracts(hotel_id, name);

create table if not exists hotel_contract_versions (
  id integer generated by default as identity primary key,
  hotel_contract_id integer not null references hotel_contracts(id) on delete cascade,
  version_name text not null,
  valid_from date not null,
  valid_to date not null,
  booking_from date,
  booking_to date,
  issued_at date,
  supersedes_version_id integer references hotel_contract_versions(id),
  is_active boolean not null default false,
  source_document_name text,
  source_document_url text,
  notes text,
  created_at timestamptz not null default now(),
  check (valid_to >= valid_from),
  check (booking_from is null or booking_to is null or booking_to >= booking_from)
);

create unique index if not exists hotel_contract_versions_name_uq
  on hotel_contract_versions(hotel_contract_id, version_name);

create index if not exists hotel_contract_versions_active_idx
  on hotel_contract_versions(hotel_contract_id, is_active);

create table if not exists hotel_contract_seasons (
  id integer generated by default as identity primary key,
  contract_version_id integer not null references hotel_contract_versions(id) on delete cascade,
  season_code text not null,
  season_name text not null,
  travel_from date not null,
  travel_to date not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  check (travel_to >= travel_from)
);

create unique index if not exists hotel_contract_seasons_code_uq
  on hotel_contract_seasons(contract_version_id, season_code);

create index if not exists hotel_contract_seasons_window_idx
  on hotel_contract_seasons(contract_version_id, travel_from, travel_to);

create table if not exists hotel_room_contracts (
  id integer generated by default as identity primary key,
  contract_version_id integer not null references hotel_contract_versions(id) on delete cascade,
  room_name text not null,
  room_code text,
  room_group text,
  min_pax integer,
  max_pax integer,
  max_adults integer,
  max_children integer,
  max_infants integer,
  room_notes text,
  created_at timestamptz not null default now(),
  check (min_pax is null or min_pax >= 0),
  check (max_pax is null or max_pax >= 0),
  check (max_adults is null or max_adults >= 0),
  check (max_children is null or max_children >= 0),
  check (max_infants is null or max_infants >= 0)
);

create unique index if not exists hotel_room_contracts_room_uq
  on hotel_room_contracts(contract_version_id, room_name);

create table if not exists hotel_room_rates (
  id integer generated by default as identity primary key,
  room_contract_id integer not null references hotel_room_contracts(id) on delete cascade,
  season_id integer not null references hotel_contract_seasons(id) on delete cascade,
  board_basis text not null,
  pricing_model text not null check (pricing_model in ('per_person_per_night', 'per_room_per_night', 'per_unit_per_stay')),
  rate_value numeric(12, 2),
  rate_unit text,
  single_rate_value numeric(12, 2),
  triple_rate_value numeric(12, 2),
  currency text not null default 'GBP',
  notes text,
  created_at timestamptz not null default now()
);

create unique index if not exists hotel_room_rates_lookup_uq
  on hotel_room_rates(room_contract_id, season_id, board_basis);

create table if not exists hotel_room_occupancy_rates (
  id integer generated by default as identity primary key,
  room_rate_id integer not null references hotel_room_rates(id) on delete cascade,
  occupancy_code text not null,
  adults integer not null default 2,
  children integer not null default 0,
  infants integer not null default 0,
  age_band_code text,
  rate_value numeric(12, 2) not null,
  notes text,
  created_at timestamptz not null default now(),
  check (adults >= 0),
  check (children >= 0),
  check (infants >= 0)
);

create unique index if not exists hotel_room_occupancy_rates_lookup_uq
  on hotel_room_occupancy_rates(room_rate_id, occupancy_code, adults, children, infants, coalesce(age_band_code, ''));

create table if not exists hotel_child_policies (
  id integer generated by default as identity primary key,
  contract_version_id integer not null references hotel_contract_versions(id) on delete cascade,
  room_contract_id integer references hotel_room_contracts(id) on delete cascade,
  board_basis text,
  child_band_name text not null,
  age_from integer not null,
  age_to integer not null,
  pricing_method text not null check (pricing_method in ('percentage_discount', 'fixed_rate_per_night', 'free', 'same_as_adult')),
  value numeric(12, 2),
  applies_when_sharing_with text,
  max_children_at_this_rule integer,
  priority integer not null default 100,
  notes text,
  created_at timestamptz not null default now(),
  check (age_to >= age_from),
  check (max_children_at_this_rule is null or max_children_at_this_rule >= 0)
);

create index if not exists hotel_child_policies_lookup_idx
  on hotel_child_policies(contract_version_id, room_contract_id, board_basis, age_from, age_to, priority);

create table if not exists hotel_supplements (
  id integer generated by default as identity primary key,
  contract_version_id integer not null references hotel_contract_versions(id) on delete cascade,
  room_contract_id integer references hotel_room_contracts(id) on delete cascade,
  season_id integer references hotel_contract_seasons(id) on delete cascade,
  supplement_type text not null,
  board_from text,
  board_to text,
  pricing_method text not null check (pricing_method in ('percentage', 'fixed_amount', 'fixed_rate_per_night', 'upgrade')),
  value numeric(12, 2) not null default 0,
  per_person boolean not null default true,
  per_night boolean not null default true,
  age_from integer,
  age_to integer,
  notes text,
  created_at timestamptz not null default now(),
  check (age_from is null or age_from >= 0),
  check (age_to is null or age_to >= 0),
  check (age_from is null or age_to is null or age_to >= age_from)
);

create index if not exists hotel_supplements_lookup_idx
  on hotel_supplements(contract_version_id, room_contract_id, season_id, supplement_type);

create table if not exists hotel_compulsory_charges (
  id integer generated by default as identity primary key,
  contract_version_id integer not null references hotel_contract_versions(id) on delete cascade,
  charge_name text not null,
  charge_code text,
  pricing_method text not null check (pricing_method in ('fixed_amount', 'fixed_rate_per_night', 'percentage')),
  value numeric(12, 2) not null default 0,
  per_person boolean not null default true,
  per_night boolean not null default false,
  stay_date_from date not null,
  stay_date_to date not null,
  booking_date_from date,
  booking_date_to date,
  age_from integer,
  age_to integer,
  notes text,
  created_at timestamptz not null default now(),
  check (stay_date_to >= stay_date_from),
  check (booking_date_from is null or booking_date_to is null or booking_date_to >= booking_date_from),
  check (age_from is null or age_from >= 0),
  check (age_to is null or age_to >= 0),
  check (age_from is null or age_to is null or age_to >= age_from)
);

create index if not exists hotel_compulsory_charges_lookup_idx
  on hotel_compulsory_charges(contract_version_id, stay_date_from, stay_date_to);

create table if not exists hotel_offers (
  id integer generated by default as identity primary key,
  contract_version_id integer not null references hotel_contract_versions(id) on delete cascade,
  offer_code text not null,
  offer_name text not null,
  offer_family text not null check (offer_family in ('percentage_discount', 'fixed_discount', 'free_night', 'stay_pay', 'meal_plan_upgrade', 'child_discount', 'honeymoon', 'anniversary', 'repeat_guest', 'early_booking', 'long_stay', 'booking_window_extension')),
  status text not null default 'draft' check (status in ('draft', 'active', 'archived')),
  booking_from date,
  booking_to date,
  travel_from date,
  travel_to date,
  minimum_nights integer,
  maximum_nights integer,
  description text,
  priority integer not null default 100,
  stop_after_apply boolean not null default false,
  notes text,
  created_at timestamptz not null default now(),
  check (booking_from is null or booking_to is null or booking_to >= booking_from),
  check (travel_from is null or travel_to is null or travel_to >= travel_from),
  check (minimum_nights is null or minimum_nights >= 0),
  check (maximum_nights is null or maximum_nights >= 0)
);

create unique index if not exists hotel_offers_code_uq
  on hotel_offers(contract_version_id, offer_code);

create index if not exists hotel_offers_priority_idx
  on hotel_offers(contract_version_id, priority, status);

create table if not exists hotel_offer_rules (
  id integer generated by default as identity primary key,
  hotel_offer_id integer not null references hotel_offers(id) on delete cascade,
  rule_type text not null check (rule_type in ('percentage_discount', 'fixed_discount', 'free_night', 'stay_pay', 'meal_plan_upgrade', 'child_discount', 'compulsory_charge')),
  target_scope text not null default 'stay' check (target_scope in ('stay', 'room', 'board', 'night', 'guest', 'child', 'teen')),
  pricing_method text not null check (pricing_method in ('percentage', 'fixed_amount', 'free_night', 'upgrade')),
  value numeric(12, 2),
  age_from integer,
  age_to integer,
  room_name text,
  board_basis text,
  day_of_week integer,
  free_night_pattern text,
  apply_stage text not null default 'offers' check (apply_stage in ('pre_child', 'child_pricing', 'pre_supplements', 'supplements', 'compulsory', 'offers', 'post_offers')),
  sort_order integer not null default 0,
  notes text,
  created_at timestamptz not null default now(),
  check (day_of_week is null or (day_of_week >= 0 and day_of_week <= 6)),
  check (age_from is null or age_from >= 0),
  check (age_to is null or age_to >= 0),
  check (age_from is null or age_to is null or age_to >= age_from)
);

create index if not exists hotel_offer_rules_lookup_idx
  on hotel_offer_rules(hotel_offer_id, apply_stage, sort_order);

create table if not exists hotel_offer_combinability (
  id integer generated by default as identity primary key,
  hotel_offer_id integer not null references hotel_offers(id) on delete cascade,
  with_offer_family text,
  with_offer_code text,
  is_allowed boolean not null default false,
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists hotel_offer_combinability_lookup_idx
  on hotel_offer_combinability(hotel_offer_id, with_offer_family, with_offer_code);

create table if not exists hotel_pricing_test_cases (
  id integer generated by default as identity primary key,
  hotel_id integer not null references hotel_list(id) on delete cascade,
  contract_version_id integer references hotel_contract_versions(id) on delete set null,
  label text not null,
  booking_date date not null,
  check_in_date date not null,
  check_out_date date not null,
  room_name text not null,
  board_basis text not null,
  adults integer not null default 2,
  child_ages integer[] not null default '{}'::integer[],
  teen_ages integer[] not null default '{}'::integer[],
  infants integer not null default 0,
  expected_net numeric(12, 2),
  expected_applied_offer_codes text[] not null default '{}'::text[],
  expected_rejected_offer_codes text[] not null default '{}'::text[],
  notes text,
  created_at timestamptz not null default now(),
  check (check_out_date > check_in_date),
  check (adults >= 0),
  check (infants >= 0)
);

create index if not exists hotel_pricing_test_cases_lookup_idx
  on hotel_pricing_test_cases(hotel_id, contract_version_id, booking_date, check_in_date);
