ALTER TABLE staff_users
ALTER COLUMN role SET DEFAULT 'sales';

ALTER TABLE clients
ADD COLUMN IF NOT EXISTS owner_staff_id integer REFERENCES staff_users(id);

ALTER TABLE deals
ADD COLUMN IF NOT EXISTS staff_id integer REFERENCES staff_users(id);

ALTER TABLE bookings
ADD COLUMN IF NOT EXISTS balance_cleared_at timestamptz;

CREATE TABLE IF NOT EXISTS audit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type text NOT NULL,
  entity_id bigint NOT NULL,
  action text NOT NULL,
  field_name text,
  old_value jsonb,
  new_value jsonb,
  performed_by_staff_id integer REFERENCES staff_users(id),
  performed_by_role text,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO audit_log (entity_type, entity_id, action, notes)
SELECT 'system', 0, 'bootstrap', 'Audit log initialized'
WHERE NOT EXISTS (SELECT 1 FROM audit_log);

UPDATE staff_users
SET role = 'manager'
WHERE name = 'Samir Abattouy';

UPDATE clients
SET owner_staff_id = staff_users.id
FROM staff_users
WHERE clients.owner_staff_id IS NULL
  AND staff_users.name = 'Samir Abattouy';

UPDATE deals
SET staff_id = clients.owner_staff_id
FROM clients
WHERE deals.client_id = clients.id
  AND deals.staff_id IS NULL
  AND clients.owner_staff_id IS NOT NULL;

UPDATE bookings
SET staff_id = deals.staff_id
FROM deals
WHERE bookings.deal_id = deals.id
  AND bookings.staff_id IS NULL
  AND deals.staff_id IS NOT NULL;

UPDATE bookings
SET balance_cleared_at = now()
FROM (
  SELECT booking_id, SUM(amount) AS total_paid
  FROM booking_payments
  GROUP BY booking_id
) payments
WHERE bookings.id = payments.booking_id
  AND COALESCE(bookings.total_sell, 0) > 0
  AND payments.total_paid >= bookings.total_sell
  AND bookings.balance_cleared_at IS NULL;
