-- ── BOOKING OWNERSHIP CLAIMS ─────────────────────────────────
create table if not exists booking_ownership_claims (
  id              bigint generated by default as identity primary key,
  booking_id      bigint not null references bookings(id) on delete cascade,
  claimant_id     integer not null references staff_users(id),
  reason          text not null,
  status          text not null default 'pending'
                  check (status in ('pending', 'approved', 'rejected')),
  reviewed_by     integer references staff_users(id),
  review_notes    text,
  approved_split  numeric(5,2),
  created_at      timestamptz not null default now(),
  reviewed_at     timestamptz
);

-- one pending claim per (booking, claimant) at a time
create unique index if not exists booking_ownership_claims_pending_uidx
  on booking_ownership_claims (booking_id, claimant_id)
  where status = 'pending';

-- ── BOOKING OWNERSHIP HISTORY ─────────────────────────────────
-- append-only — never updated after insert
create table if not exists booking_ownership_history (
  id                        bigint generated by default as identity primary key,
  booking_id                bigint not null references bookings(id) on delete cascade,
  changed_by                integer references staff_users(id),
  change_type               text not null
                            check (change_type in (
                              'initial_assignment',
                              'manager_reassignment',
                              'claim_approved',
                              'claim_rejected',
                              'repeat_client_enforcement'
                            )),
  previous_primary_staff_id integer references staff_users(id),
  new_primary_staff_id      integer references staff_users(id),
  commission_snapshot       jsonb,
  claim_id                  bigint references booking_ownership_claims(id),
  notes                     text,
  created_at                timestamptz not null default now()
);

create index if not exists booking_ownership_history_booking_idx
  on booking_ownership_history (booking_id);

-- ── CLIENT REPEAT FLAGS ───────────────────────────────────────
create table if not exists client_repeat_flags (
  id                 bigint generated by default as identity primary key,
  client_id          bigint not null references clients(id) on delete cascade,
  booking_id         bigint not null references bookings(id) on delete cascade,
  original_staff_id  integer references staff_users(id),
  handling_staff_id  integer references staff_users(id),
  flagged_at         timestamptz not null default now(),
  resolved_by        integer references staff_users(id),
  resolution         text check (resolution in (
                       'enforced_50_50',
                       'reassigned_to_original',
                       'manager_override',
                       'dismissed'
                     )),
  resolved_at        timestamptz
);

create unique index if not exists client_repeat_flags_booking_uidx
  on client_repeat_flags (booking_id);

create index if not exists client_repeat_flags_client_idx
  on client_repeat_flags (client_id);

-- Backfill initial_assignment history for existing bookings that have a staff_id
insert into booking_ownership_history (
  booking_id, change_type, new_primary_staff_id,
  commission_snapshot, notes
)
select
  b.id,
  'initial_assignment',
  b.staff_id,
  jsonb_build_array(
    jsonb_build_object(
      'staff_id', bc.staff_id,
      'share_percent', bc.share_percent,
      'is_primary', bc.is_primary
    )
  ),
  'Backfilled on migration'
from bookings b
join booking_commissions bc on bc.booking_id = b.id and bc.is_primary = true
where b.staff_id is not null
  and not exists (
    select 1 from booking_ownership_history boh where boh.booking_id = b.id
  );
