
-- ── 1. Widen booking_profit_events.type ──────────────────────────────────────
alter table booking_profit_events
  drop constraint if exists booking_profit_events_type_check;

alter table booking_profit_events
  add constraint booking_profit_events_type_check
    check (type in ('original', 'amendment', 'recognition', 'split_correction'));

-- ── 2. Add commissionable flag ────────────────────────────────────────────────
alter table booking_profit_events
  add column if not exists commissionable boolean not null default false;

-- ── 3. Add recognition_period ('YYYY-MM') ────────────────────────────────────
alter table booking_profit_events
  add column if not exists recognition_period text
    check (recognition_period ~ '^\d{4}-\d{2}$');

-- ── 4. Backfill existing rows ─────────────────────────────────────────────────
update booking_profit_events bpe
set
  commissionable      = true,
  recognition_period  = to_char(b.balance_cleared_at at time zone 'UTC', 'YYYY-MM')
from bookings b
where bpe.booking_id = b.id
  and b.balance_cleared_at is not null
  and bpe.type in ('original', 'amendment', 'recognition', 'split_correction');

-- ── 5. commission_cycles ──────────────────────────────────────────────────────
create table if not exists commission_cycles (
  id         bigint generated by default as identity primary key,
  period     text        not null unique
               check (period ~ '^\d{4}-\d{2}$'),
  status     text        not null default 'open'
               check (status in ('open', 'locked')),
  locked_at  timestamptz,
  locked_by  integer references staff_users(id),
  created_at timestamptz not null default now()
);
;
